version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: template-express-lambda-typescript
        ports:
            - 3000:3000
        volumes:
            - ./:/app